<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;

class CustomerSeeder extends Seeder
{
    public function run()
    {
        $customers = [
            [
                'name' => 'Max Mustermann',
                'customer_number' => 'KD-001',
                'company_name' => null,
                'contact_person' => null,
                'department' => null,
                'email' => 'max.mustermann@email.de',
                'phone' => '+49 30 12345678',
                'fax' => null,
                'website' => null,
                'street' => 'Musterstraße 123',
                'address_line_2' => null,
                'postal_code' => '10115',
                'city' => 'Berlin',
                'state' => 'Berlin',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => null,
                'vat_id' => null,
                'payment_terms' => 'Zahlung innerhalb von 14 Tagen netto',
                'payment_days' => 14,
                'bank_name' => 'Berliner Sparkasse',
                'iban' => 'DE10100500001234567890',
                'bic' => 'BELADEBEXXX',
                'notes' => 'Privatkunde mit Solaranlage auf Einfamilienhaus',
                'is_active' => true,
                'customer_type' => 'private',
            ],
            [
                'name' => 'Anna Schmidt',
                'customer_number' => 'KD-002',
                'company_name' => null,
                'contact_person' => null,
                'department' => null,
                'email' => 'anna.schmidt@gmx.de',
                'phone' => '+49 89 98765432',
                'fax' => null,
                'website' => null,
                'street' => 'Sonnenallee 45',
                'address_line_2' => 'Hinterhaus',
                'postal_code' => '80331',
                'city' => 'München',
                'state' => 'Bayern',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => null,
                'vat_id' => null,
                'payment_terms' => 'Zahlung innerhalb von 30 Tagen netto',
                'payment_days' => 30,
                'bank_name' => 'Stadtsparkasse München',
                'iban' => 'DE70701500001234567891',
                'bic' => 'SSKMDEMMXXX',
                'notes' => 'Interessiert an Batteriespeicher-Erweiterung',
                'is_active' => true,
                'customer_type' => 'private',
            ],
            [
                'name' => 'Weber Maschinenbau GmbH',
                'customer_number' => 'KD-003',
                'company_name' => 'Weber Maschinenbau GmbH',
                'contact_person' => 'Thomas Weber',
                'department' => 'Geschäftsführung',
                'email' => 'info@weber-maschinenbau.de',
                'phone' => '+49 711 555-0',
                'fax' => '+49 711 555-199',
                'website' => 'www.weber-maschinenbau.de',
                'street' => 'Industriestraße 15',
                'address_line_2' => 'Gebäude A, Tor 3',
                'postal_code' => '70173',
                'city' => 'Stuttgart',
                'state' => 'Baden-Württemberg',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '99123/12345',
                'vat_id' => 'DE123456789',
                'payment_terms' => 'Zahlung innerhalb von 30 Tagen netto, 2% Skonto bei Zahlung innerhalb von 10 Tagen',
                'payment_days' => 30,
                'bank_name' => 'Landesbank Baden-Württemberg',
                'iban' => 'DE89600501010001234567',
                'bic' => 'SOLADEST600',
                'notes' => 'Großkunde - Solaranlage für Produktionshalle 500 kWp',
                'is_active' => true,
                'customer_type' => 'business',
            ],
            [
                'name' => 'Müller Bäckerei & Konditorei',
                'customer_number' => 'KD-004',
                'company_name' => 'Müller Bäckerei & Konditorei GmbH',
                'contact_person' => 'Petra Müller',
                'department' => 'Inhaberin',
                'email' => 'petra@mueller-baeckerei.de',
                'phone' => '+49 40 777888',
                'fax' => '+49 40 777889',
                'website' => 'www.mueller-baeckerei.de',
                'street' => 'Hauptstraße 67',
                'address_line_2' => null,
                'postal_code' => '20095',
                'city' => 'Hamburg',
                'state' => 'Hamburg',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '17/123/45678',
                'vat_id' => 'DE987654321',
                'payment_terms' => 'Zahlung sofort ohne Abzug',
                'payment_days' => 0,
                'bank_name' => 'Hamburger Sparkasse',
                'iban' => 'DE12200505501234567890',
                'bic' => 'HASPDEHHXXX',
                'notes' => 'Kleine Solaranlage für Bäckerei - 25 kWp auf Flachdach',
                'is_active' => true,
                'customer_type' => 'business',
            ],
            [
                'name' => 'Hoffmann Rechtsanwaltskanzlei',
                'customer_number' => 'KD-005',
                'company_name' => 'Hoffmann Rechtsanwaltskanzlei PartG mbB',
                'contact_person' => 'Dr. Michael Hoffmann',
                'department' => 'Rechtsanwalt und Partner',
                'email' => 'kanzlei@hoffmann-recht.de',
                'phone' => '+49 221 333444',
                'fax' => '+49 221 333445',
                'website' => 'www.hoffmann-recht.de',
                'street' => 'Domstraße 12',
                'address_line_2' => '3. Etage, Büro 301-305',
                'postal_code' => '50667',
                'city' => 'Köln',
                'state' => 'Nordrhein-Westfalen',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '214/5678/9012',
                'vat_id' => 'DE456789123',
                'payment_terms' => 'Zahlung innerhalb von 14 Tagen netto',
                'payment_days' => 14,
                'bank_name' => 'Kreissparkasse Köln',
                'iban' => 'DE34370502990000012345',
                'bic' => 'COLSDE33XXX',
                'notes' => 'Kanzleigebäude mit Solaranlage - 40 kWp',
                'is_active' => true,
                'customer_type' => 'business',
            ],
            [
                'name' => 'Familie Schneider',
                'customer_number' => 'KD-006',
                'company_name' => null,
                'contact_person' => 'Klaus Schneider',
                'department' => null,
                'email' => 'k.schneider@web.de',
                'phone' => '+49 351 666777',
                'fax' => null,
                'website' => null,
                'street' => 'Gartenstraße 89',
                'address_line_2' => null,
                'postal_code' => '01309',
                'city' => 'Dresden',
                'state' => 'Sachsen',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => null,
                'vat_id' => null,
                'payment_terms' => 'Zahlung bei Lieferung',
                'payment_days' => 0,
                'bank_name' => 'Ostsächsische Sparkasse Dresden',
                'iban' => 'DE85850503000000123456',
                'bic' => 'OSDDDE81XXX',
                'notes' => 'Einfamilienhaus mit Süddach - optimale Ausrichtung',
                'is_active' => true,
                'customer_type' => 'private',
            ],
            [
                'name' => 'Fischer Landwirtschaft',
                'customer_number' => 'KD-007',
                'company_name' => 'Fischer Landwirtschaft GbR',
                'contact_person' => 'Sabine Fischer',
                'department' => 'Betriebsleiterin',
                'email' => 'info@fischer-hof.de',
                'phone' => '+49 5121 888999',
                'fax' => '+49 5121 888998',
                'website' => 'www.fischer-hof.de',
                'street' => 'Dorfstraße 23',
                'address_line_2' => 'Hof Fischer',
                'postal_code' => '31134',
                'city' => 'Hildesheim',
                'state' => 'Niedersachsen',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '25/123/67890',
                'vat_id' => 'DE789123456',
                'payment_terms' => 'Zahlung innerhalb von 60 Tagen netto',
                'payment_days' => 60,
                'bank_name' => 'Volksbank Hildesheim eG',
                'iban' => 'DE56259900070000123456',
                'bic' => 'GENODEF1HIL',
                'notes' => 'Große Solaranlage für Scheunendach - 200 kWp Agri-PV',
                'is_active' => true,
                'customer_type' => 'business',
            ],
            [
                'name' => 'Robert Klein',
                'customer_number' => 'KD-008',
                'company_name' => null,
                'contact_person' => null,
                'department' => null,
                'email' => 'robert.klein@outlook.de',
                'phone' => '+49 69 111222',
                'fax' => null,
                'website' => null,
                'street' => 'Friedensstraße 156',
                'address_line_2' => 'Erdgeschoss',
                'postal_code' => '60323',
                'city' => 'Frankfurt am Main',
                'state' => 'Hessen',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => null,
                'vat_id' => null,
                'payment_terms' => 'Zahlung innerhalb von 21 Tagen netto',
                'payment_days' => 21,
                'bank_name' => 'Frankfurter Sparkasse',
                'iban' => 'DE11500502010000123456',
                'bic' => 'HELADEF1822',
                'notes' => 'Reihenhaus mit Ost-West-Ausrichtung - 12 kWp',
                'is_active' => true,
                'customer_type' => 'private',
            ],
            [
                'name' => 'TechStart Innovation GmbH',
                'customer_number' => 'KD-009',
                'company_name' => 'TechStart Innovation GmbH',
                'contact_person' => 'Lisa Innovativ',
                'department' => 'Geschäftsführung',
                'email' => 'info@techstart-innovation.de',
                'phone' => '+49 30 987654321',
                'fax' => '+49 30 987654322',
                'website' => 'www.techstart-innovation.de',
                'street' => 'Startup-Allee 42',
                'address_line_2' => 'TechHub Berlin, Etage 5',
                'postal_code' => '10178',
                'city' => 'Berlin',
                'state' => 'Berlin',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '37/123/98765',
                'vat_id' => 'DE321654987',
                'payment_terms' => 'Zahlung innerhalb von 14 Tagen netto, 3% Skonto bei Zahlung innerhalb von 7 Tagen',
                'payment_days' => 14,
                'bank_name' => 'Deutsche Bank AG',
                'iban' => 'DE89100700000123456789',
                'bic' => 'DEUTDEBBXXX',
                'notes' => 'Startup-Unternehmen - Solaranlage für Bürogebäude 75 kWp',
                'is_active' => true,
                'customer_type' => 'business',
            ],
            [
                'name' => 'Maria Gonzalez',
                'customer_number' => 'KD-010',
                'company_name' => null,
                'contact_person' => null,
                'department' => null,
                'email' => 'maria.gonzalez@gmail.com',
                'phone' => '+49 89 555123456',
                'fax' => null,
                'website' => null,
                'street' => 'Rosenheimer Straße 234',
                'address_line_2' => '2. Stock, Wohnung 15',
                'postal_code' => '81669',
                'city' => 'München',
                'state' => 'Bayern',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => null,
                'vat_id' => null,
                'payment_terms' => 'Zahlung innerhalb von 30 Tagen netto',
                'payment_days' => 30,
                'bank_name' => 'HypoVereinsbank',
                'iban' => 'DE21700202700000123457',
                'bic' => 'HYVEDEMMXXX',
                'notes' => 'Eigentumswohnung mit Balkon-Solaranlage - 2 kWp Balkonkraftwerk',
                'is_active' => true,
                'customer_type' => 'private',
            ],
        ];

        foreach ($customers as $customerData) {
            Customer::create($customerData);
        }
    }
}
