<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Supplier;

class SupplierSeeder extends Seeder
{
    public function run()
    {
        $suppliers = [
            [
                'name' => 'SolarTech Deutschland GmbH',
                'supplier_number' => 'LF-001',
                'company_name' => 'SolarTech Deutschland GmbH',
                'contact_person' => 'Markus Solarmann',
                'department' => 'Vertrieb',
                'email' => 'vertrieb@solartech-deutschland.de',
                'phone' => '+49 89 123456-0',
                'fax' => '+49 89 123456-99',
                'website' => 'www.solartech-deutschland.de',
                'street' => 'Solarstraße 25',
                'address_line_2' => 'Gewerbepark Süd, Halle 7',
                'postal_code' => '85748',
                'city' => 'Garching',
                'state' => 'Bayern',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '143/123/45678',
                'vat_id' => 'DE123456789',
                'commercial_register' => 'HRB 234567 München',
                'bank_name' => 'Commerzbank AG',
                'iban' => 'DE89700800000123456789',
                'bic' => 'DRESDEFF700',
                'account_holder' => 'SolarTech Deutschland GmbH',
                'payment_terms' => 'Zahlung innerhalb von 30 Tagen netto, 2% Skonto bei Zahlung innerhalb von 10 Tagen',
                'payment_days' => 30,
                'discount_percentage' => 2.00,
                'discount_days' => 10,
                'notes' => 'Hauptlieferant für Solarmodule und Wechselrichter - Premium-Partner',
                'is_active' => true,
            ],
            [
                'name' => 'Energiespeicher Nord AG',
                'supplier_number' => 'LF-002',
                'company_name' => 'Energiespeicher Nord AG',
                'contact_person' => 'Dr. Andrea Batterie',
                'department' => 'Technischer Vertrieb',
                'email' => 'info@energiespeicher-nord.de',
                'phone' => '+49 40 987654-0',
                'fax' => '+49 40 987654-99',
                'website' => 'www.energiespeicher-nord.de',
                'street' => 'Batterieweg 12',
                'address_line_2' => 'Industriegebiet Nord',
                'postal_code' => '22761',
                'city' => 'Hamburg',
                'state' => 'Hamburg',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '17/987/65432',
                'vat_id' => 'DE987654321',
                'commercial_register' => 'HRB 345678 Hamburg',
                'bank_name' => 'Hamburger Sparkasse',
                'iban' => 'DE12200505501987654321',
                'bic' => 'HASPDEHHXXX',
                'account_holder' => 'Energiespeicher Nord AG',
                'payment_terms' => 'Zahlung innerhalb von 45 Tagen netto',
                'payment_days' => 45,
                'discount_percentage' => null,
                'discount_days' => null,
                'notes' => 'Spezialist für Batteriespeichersysteme - Lithium-Ionen und LFP',
                'is_active' => true,
            ],
            [
                'name' => 'Montage-Profis Rheinland GmbH',
                'supplier_number' => 'LF-003',
                'company_name' => 'Montage-Profis Rheinland GmbH',
                'contact_person' => 'Stefan Dachdecker',
                'department' => 'Projektleitung',
                'email' => 'projekte@montage-profis.de',
                'phone' => '+49 221 555777-0',
                'fax' => '+49 221 555777-99',
                'website' => 'www.montage-profis.de',
                'street' => 'Handwerkerstraße 89',
                'address_line_2' => 'Gewerbehof Rheinland',
                'postal_code' => '50823',
                'city' => 'Köln',
                'state' => 'Nordrhein-Westfalen',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '214/456/78901',
                'vat_id' => 'DE456789012',
                'commercial_register' => 'HRB 456789 Köln',
                'bank_name' => 'Kreissparkasse Köln',
                'iban' => 'DE34370502990987654321',
                'bic' => 'COLSDE33XXX',
                'account_holder' => 'Montage-Profis Rheinland GmbH',
                'payment_terms' => 'Zahlung innerhalb von 14 Tagen netto',
                'payment_days' => 14,
                'discount_percentage' => null,
                'discount_days' => null,
                'notes' => 'Zuverlässiger Montagepartner für Solaranlagen - Dach und Freifläche',
                'is_active' => true,
            ],
            [
                'name' => 'ElektroTechnik Ost GmbH',
                'supplier_number' => 'LF-004',
                'company_name' => 'ElektroTechnik Ost GmbH',
                'contact_person' => 'Jürgen Elektriker',
                'department' => 'Service & Installation',
                'email' => 'service@elektrotechnik-ost.de',
                'phone' => '+49 351 444555-0',
                'fax' => '+49 351 444555-99',
                'website' => 'www.elektrotechnik-ost.de',
                'street' => 'Stromstraße 45',
                'address_line_2' => 'Industriegebiet Nord, Halle 12',
                'postal_code' => '01109',
                'city' => 'Dresden',
                'state' => 'Sachsen',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '203/789/01234',
                'vat_id' => 'DE789012345',
                'commercial_register' => 'HRB 567890 Dresden',
                'bank_name' => 'Ostsächsische Sparkasse Dresden',
                'iban' => 'DE85850503000987654321',
                'bic' => 'OSDDDE81XXX',
                'account_holder' => 'ElektroTechnik Ost GmbH',
                'payment_terms' => 'Zahlung innerhalb von 21 Tagen netto',
                'payment_days' => 21,
                'discount_percentage' => null,
                'discount_days' => null,
                'notes' => 'Elektrische Installationen und Netzanschlüsse - zertifizierter Fachbetrieb',
                'is_active' => true,
            ],
            [
                'name' => 'Green Energy Components Ltd.',
                'supplier_number' => 'LF-005',
                'company_name' => 'Green Energy Components Ltd.',
                'contact_person' => 'James Greenfield',
                'department' => 'International Sales',
                'email' => 'sales@green-energy-components.co.uk',
                'phone' => '+44 20 7123 4567',
                'fax' => '+44 20 7123 4568',
                'website' => 'www.green-energy-components.co.uk',
                'street' => '123 Solar Avenue',
                'address_line_2' => 'Industrial Estate, Unit 15',
                'postal_code' => 'SW1A 1AA',
                'city' => 'London',
                'state' => 'England',
                'country' => 'Vereinigtes Königreich',
                'country_code' => 'GB',
                'tax_number' => 'GB123456789',
                'vat_id' => 'GB123456789',
                'commercial_register' => 'Companies House 12345678',
                'bank_name' => 'Barclays Bank PLC',
                'iban' => 'GB82BARC20000012345678',
                'bic' => 'BARCGB22XXX',
                'account_holder' => 'Green Energy Components Ltd.',
                'payment_terms' => 'Payment within 30 days net, 2% discount within 14 days',
                'payment_days' => 30,
                'discount_percentage' => 2.00,
                'discount_days' => 14,
                'notes' => 'Internationaler Lieferant für Spezialkomponenten - Optimierer und Monitoring',
                'is_active' => true,
            ],
            [
                'name' => 'Kabel & Mehr Handels GmbH',
                'supplier_number' => 'LF-006',
                'company_name' => 'Kabel & Mehr Handels GmbH',
                'contact_person' => 'Petra Kabelmann',
                'department' => 'Einkauf & Vertrieb',
                'email' => 'einkauf@kabel-mehr.de',
                'phone' => '+49 711 333444-0',
                'fax' => '+49 711 333444-99',
                'website' => 'www.kabel-mehr.de',
                'street' => 'Kabelstraße 67',
                'address_line_2' => 'Logistikzentrum Süd',
                'postal_code' => '70469',
                'city' => 'Stuttgart',
                'state' => 'Baden-Württemberg',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '99/345/67890',
                'vat_id' => 'DE345678901',
                'commercial_register' => 'HRB 678901 Stuttgart',
                'bank_name' => 'Landesbank Baden-Württemberg',
                'iban' => 'DE89600501010987654321',
                'bic' => 'SOLADEST600',
                'account_holder' => 'Kabel & Mehr Handels GmbH',
                'payment_terms' => 'Zahlung innerhalb von 30 Tagen netto, 3% Skonto bei Zahlung innerhalb von 8 Tagen',
                'payment_days' => 30,
                'discount_percentage' => 3.00,
                'discount_days' => 8,
                'notes' => 'Großhändler für Elektromaterial und Kabel - DC/AC-Kabel, Steckverbinder',
                'is_active' => true,
            ],
            [
                'name' => 'Solartechnik Bayern e.K.',
                'supplier_number' => 'LF-007',
                'company_name' => 'Solartechnik Bayern e.K.',
                'contact_person' => 'Hans Sonnenschein',
                'department' => 'Inhaber',
                'email' => 'info@solartechnik-bayern.de',
                'phone' => '+49 8031 222333',
                'fax' => '+49 8031 222334',
                'website' => 'www.solartechnik-bayern.de',
                'street' => 'Alpenstraße 12',
                'address_line_2' => null,
                'postal_code' => '83022',
                'city' => 'Rosenheim',
                'state' => 'Bayern',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '156/234/56789',
                'vat_id' => 'DE234567890',
                'commercial_register' => null,
                'bank_name' => 'Sparkasse Rosenheim-Bad Aibling',
                'iban' => 'DE56711525700987654321',
                'bic' => 'BYLADEM1ROS',
                'account_holder' => 'Hans Sonnenschein',
                'payment_terms' => 'Zahlung innerhalb von 14 Tagen netto',
                'payment_days' => 14,
                'discount_percentage' => null,
                'discount_days' => null,
                'notes' => 'Regionaler Anbieter für Solartechnik - Kleinteile und Befestigungssysteme',
                'is_active' => true,
            ],
            [
                'name' => 'Wartung & Service Nord GmbH',
                'supplier_number' => 'LF-008',
                'company_name' => 'Wartung & Service Nord GmbH',
                'contact_person' => 'Michael Servicemann',
                'department' => 'Technischer Service',
                'email' => 'service@wartung-nord.de',
                'phone' => '+49 431 666777-0',
                'fax' => '+49 431 666777-99',
                'website' => 'www.wartung-nord.de',
                'street' => 'Servicestraße 34',
                'address_line_2' => 'Technikzentrum Nord',
                'postal_code' => '24103',
                'city' => 'Kiel',
                'state' => 'Schleswig-Holstein',
                'country' => 'Deutschland',
                'country_code' => 'DE',
                'tax_number' => '19/567/89012',
                'vat_id' => 'DE567890123',
                'commercial_register' => 'HRB 789012 Kiel',
                'bank_name' => 'Förde Sparkasse',
                'iban' => 'DE23210501700987654321',
                'bic' => 'NOLADE21KIE',
                'account_holder' => 'Wartung & Service Nord GmbH',
                'payment_terms' => 'Zahlung innerhalb von 30 Tagen netto',
                'payment_days' => 30,
                'discount_percentage' => null,
                'discount_days' => null,
                'notes' => 'Wartung und Reparatur von Solaranlagen - 24/7 Notdienst verfügbar',
                'is_active' => true,
            ],
            [
                'name' => 'Alpine Solar Systems AG',
                'supplier_number' => 'LF-009',
                'company_name' => 'Alpine Solar Systems AG',
                'contact_person' => 'Franz Bergmann',
                'department' => 'Verkaufsleitung Deutschland',
                'email' => 'deutschland@alpine-solar.at',
                'phone' => '+43 512 123456',
                'fax' => '+43 512 123457',
                'website' => 'www.alpine-solar.at',
                'street' => 'Bergstraße 88',
                'address_line_2' => 'Gewerbepark Alpen',
                'postal_code' => '6020',
                'city' => 'Innsbruck',
                'state' => 'Tirol',
                'country' => 'Österreich',
                'country_code' => 'AT',
                'tax_number' => 'ATU12345678',
                'vat_id' => 'ATU12345678',
                'commercial_register' => 'FN 123456a Innsbruck',
                'bank_name' => 'Raiffeisen Bank Tirol',
                'iban' => 'AT611904300987654321',
                'bic' => 'RZTIAT22XXX',
                'account_holder' => 'Alpine Solar Systems AG',
                'payment_terms' => 'Zahlung innerhalb von 30 Tagen netto',
                'payment_days' => 30,
                'discount_percentage' => null,
                'discount_days' => null,
                'notes' => 'Spezialist für Hochgebirgs-Solaranlagen - extreme Wetterbedingungen',
                'is_active' => true,
            ],
            [
                'name' => 'Swiss Solar Solutions SA',
                'supplier_number' => 'LF-010',
                'company_name' => 'Swiss Solar Solutions SA',
                'contact_person' => 'Pierre Solaire',
                'department' => 'Export Manager',
                'email' => 'export@swiss-solar.ch',
                'phone' => '+41 44 123 45 67',
                'fax' => '+41 44 123 45 68',
                'website' => 'www.swiss-solar.ch',
                'street' => 'Solarweg 15',
                'address_line_2' => 'Industriezone Ost',
                'postal_code' => '8050',
                'city' => 'Zürich',
                'state' => 'Zürich',
                'country' => 'Schweiz',
                'country_code' => 'CH',
                'tax_number' => 'CHE-123.456.789',
                'vat_id' => 'CHE-123.456.789 MWST',
                'commercial_register' => 'CH-020.3.123.456-7',
                'bank_name' => 'UBS Switzerland AG',
                'iban' => 'CH9300762011623852957',
                'bic' => 'UBSWCHZH80A',
                'account_holder' => 'Swiss Solar Solutions SA',
                'payment_terms' => 'Zahlung innerhalb von 30 Tagen netto',
                'payment_days' => 30,
                'discount_percentage' => null,
                'discount_days' => null,
                'notes' => 'Premium-Solarmodule für anspruchsvolle Anwendungen - Swiss Made Quality',
                'is_active' => true,
            ],
        ];

        foreach ($suppliers as $supplierData) {
            Supplier::create($supplierData);
        }
    }
}